[project]
name = "termibook"
version = "0.1.0"
description = "console bot"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "colorama==0.4.6",
  "prettytable==3.16.0",
  "prompt_toolkit==3.0.51",
  "wcwidth==0.2.13"
]

[project.scripts]
termibook = "src.main:main"
